'use client';

import { useEffect, useState } from 'react';
import clsx from 'clsx';
import { GlitchText } from './GlitchText';

interface RoastTextProps {
  title: string;
  body: string;
  score: number;
  className?: string;
}

export function RoastText({ title, body, score, className }: RoastTextProps) {
  const [isRevealed, setIsRevealed] = useState(false);

  useEffect(() => {
    // Delay reveal for dramatic effect
    const timer = setTimeout(() => setIsRevealed(true), 500);
    return () => clearTimeout(timer);
  }, []);

  // Determine roast intensity based on score
  const getIntensityStyles = () => {
    if (score >= 85) {
      return {
        borderClass: 'border-terminal',
        glowClass: 'shadow-terminal/20',
        titleColor: 'text-terminal',
        label: 'ACCEPTABLE',
        emoji: '🙄',
      };
    }
    if (score >= 65) {
      return {
        borderClass: 'border-neon-yellow',
        glowClass: 'shadow-neon-yellow/20',
        titleColor: 'text-neon-yellow',
        label: 'NEEDS WORK',
        emoji: '😬',
      };
    }
    if (score >= 40) {
      return {
        borderClass: 'border-neon-orange',
        glowClass: 'shadow-neon-orange/20',
        titleColor: 'text-neon-orange',
        label: 'BRUTAL',
        emoji: '🔥',
      };
    }
    return {
      borderClass: 'border-danger',
      glowClass: 'shadow-danger/20',
      titleColor: 'text-danger',
      label: 'NUCLEAR',
      emoji: '☢️',
    };
  };

  const styles = getIntensityStyles();

  return (
    <div
      className={clsx(
        'relative overflow-hidden rounded-lg border-2 p-6',
        styles.borderClass,
        'shadow-lg',
        styles.glowClass,
        'transition-all duration-500',
        isRevealed ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4',
        className
      )}
    >
      {/* Background pattern */}
      <div className="absolute inset-0 opacity-5">
        <div className="absolute inset-0 bg-grid-pattern bg-grid" />
      </div>

      {/* Intensity label */}
      <div className="flex items-center justify-between mb-4">
        <span
          className={clsx(
            'inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wider',
            'bg-void-100 border',
            styles.borderClass
          )}
        >
          <span>{styles.emoji}</span>
          <span className={styles.titleColor}>{styles.label}</span>
        </span>
        <span className="text-xs text-gray-500 font-mono">ROAST_ID: {Math.random().toString(36).slice(2, 8).toUpperCase()}</span>
      </div>

      {/* Title */}
      <h2 className={clsx('text-2xl sm:text-3xl font-bold mb-4', styles.titleColor)}>
        <GlitchText text={title} glitchIntensity="low" />
      </h2>

      {/* Body */}
      <div className="relative">
        <div className="text-gray-300 leading-relaxed whitespace-pre-wrap">
          {body}
        </div>

        {/* Scanline effect */}
        <div className="absolute inset-0 pointer-events-none bg-scanline opacity-10" />
      </div>

      {/* Footer decoration */}
      <div className="mt-6 pt-4 border-t border-void-100 flex items-center justify-between">
        <span className="text-xs text-gray-500 font-mono">
          // GENERATED BY 3RROR_K1NG
        </span>
        <div className="flex items-center gap-2">
          <span className="w-2 h-2 rounded-full bg-terminal animate-pulse" />
          <span className="text-xs text-gray-500">ANALYSIS COMPLETE</span>
        </div>
      </div>
    </div>
  );
}
